version: '3.8'

services:
  trxnslate-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: trxnslate-api:1.0    
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - user-db:/app/instance
    env_file:
      - .env
    restart: unless-stopped

volumes:
  user-db:
